//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chernovRofl.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salaries
    {
        public int RecordID { get; set; }
        public int ServID { get; set; }
        public string Month { get; set; }
        public decimal Salary { get; set; }
        public int DaysIllnes { get; set; }
        public int ProcPay { get; set; }
    
        public virtual Workers Workers { get; set; }
    }
}
